apiVersion: v1
kind: Service
metadata:
  name: db-core
spec:
  selector:
    app: db-core
  ports:
    - port: 3310
      targetPort: 3310
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-core
  template:
    metadata:
      labels:
        app: db-core
    spec:
      containers:
        - name: db-core
          image: meghna-bits/weather-db:latest
          ports:
            - containerPort: 3306
          imagePullPolicy: Always