apiVersion: v1
kind: Service
metadata:
  name: weather-core
spec:
  selector:
    app: weather-core
  ports:
    - port: 3005
      targetPort: 3005
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-core
  template:
    metadata:
      labels:
        app: weather-core
    spec:
      containers:
        - name: weather-core
          image: meghnabits/weather-core:latest
          ports:
            - containerPort: 3005
          imagePullPolicy: Always